spring:
  datasource:
    url: jdbc:mysql://localhost:3306/brandhunt?serverTimezone=Asia/Seoul
    username: root
    password: 0000
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    show-sql: false

logging:
  level:
    org.hibernate.SQL: info
