spring:
  profiles:
    active: dev
  application:
    name: BrandHunt
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

jwt:
  secret: ${JWT_SECRET}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION:1800000}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION:604800000}

app:
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:5173}

server:
  port: 8000
